### ISSUE TITLE
System.Runtime.InteropServices.COMException exception  thrown

### ISSUE THREAD

**Issue by Dhirajsakariya** [XamlAnimatedGif/WpfAnimatedGif#39]
I have used spinner as follows:

```xml
<Image x:Name="image" Height="150" Width="150"
       gif:ImageBehavior.AnimatedSource="Images/spinner_purple.gif"
       Visibility="{Binding IsBusy, Converter={dxmvvm:BooleanToVisibilityConverter Inverse=False}}"/>
```

IsBusy is the public property in ViewModel.

it set it to true when loading some data in background thread as follows:
```csharp
  private void LoadProjectType()
        {
            var worker = new BackgroundWorker();
            worker.DoWork += (o, ea) =>
            {
                //use the Dispatcher to delegate to update UI thread
                System.Windows.Application.Current.Dispatcher.Invoke(new Action(() =>
                {
                    LookupProjectType = projectTypeDataService.GetAll();
                }));
            };
            worker.RunWorkerCompleted += (o, ea) =>
            {
                IsBusy = false;
            };
            IsBusy = true;
            worker.RunWorkerAsync();
        }
```
With this implementation, I am sporadically getting below exception  and system crashes:
```

System.Runtime.InteropServices.COMException:
   at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Imaging.RenderTargetBitmap..ctor (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at WpfAnimatedGif.ImageBehavior.MakeFrame (WpfAnimatedGif, Version=1.4.14.0, Culture=neutral, PublicKeyToken=null)
   at WpfAnimatedGif.ImageBehavior.GetAnimation (WpfAnimatedGif, Version=1.4.14.0, Culture=neutral, PublicKeyToken=null)
   at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage (WpfAnimatedGif, Version=1.4.14.0, Culture=neutral, PublicKeyToken=null)
   at WpfAnimatedGif.ImageBehavior.AnimatedSourceChanged (WpfAnimatedGif, Version=1.4.14.0, Culture=neutral, PublicKeyToken=null)
   at System.Windows.DependencyObject.OnPropertyChanged (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.OnPropertyChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.NotifyPropertyChange (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.UpdateEffectiveValue (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.InvalidateProperty (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.StyleHelper.InvalidateDependents (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.StyleHelper.OnBindingValueInStyleChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpressionBase.ChangeValue (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpression.TransferValue (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpression.ScheduleTransfer (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.Data.ClrBindingWorker.OnSourceInvalidation (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependentList.InvalidateDependents (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.NotifyPropertyChange (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.UpdateEffectiveValue (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperties (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.InvalidateTreeDependentProperties (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.OnAncestorChangedInternal (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.TreeWalkHelper.OnAncestorChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.IterateChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.IterateChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.IterateChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.IterateChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1._VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.VisitNode (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.IterateChildren (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DescendentsWalker`1.StartWalk (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at MS.Internal.PrePostDescendentsWalker`1.StartWalk (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.TreeWalkHelper.InvalidateOnTreeChange (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.OnVisualParentChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Visual.FireOnVisualParentChanged (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Visual.RemoveVisualChild (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.set_TemplateChild (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.StyleHelper.ClearGeneratedSubTree (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.StyleHelper.DoTemplateInvalidations (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.StyleHelper.UpdateTemplateCache (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Controls.ContentPresenter.OnTemplateChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.OnPropertyChanged (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.OnPropertyChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.NotifyPropertyChange (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.UpdateEffectiveValue (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.SetValueCommon (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Controls.ContentPresenter.OnContentChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.OnPropertyChanged (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.FrameworkElement.OnPropertyChanged (PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.NotifyPropertyChange (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.UpdateEffectiveValue (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.SetValueCommon (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.DependencyObject.SetValue (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at DevExpress.Xpf.WindowsUI.Internal.ViewPresenter.FinishContentChanging (DevExpress.Xpf.Controls.v17.1, Version=17.1.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a)
   at DevExpress.Xpf.WindowsUI.Internal.ViewPresenter.OnStoryboardCompleted (DevExpress.Xpf.Controls.v17.1, Version=17.1.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a)
   at System.Windows.Media.Animation.Clock.FireEvent (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.Animation.TimeManager.Tick (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen (WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by thomaslevesque** [comment]
Not sure what's going on here... I haven't seen this before.
What is the exception message? You only posted the stack trace.

**Comment by Dhirajsakariya** [comment]
This is from the production. System crashes. We log this within ApplicationInsight.

**Comment by thomaslevesque** [comment]
OK... I assume you don't have the HRESULT for the COM exception?
Sorry, but I don't have enough information to work with... I would need at least a meaningful error message or a way to consistently reproduce the problem.

**Comment by Dhirajsakariya** [comment]
I am getting only this info in my application insight and app crashed.

Could you please suggest how can I capture more details.

**Comment by thomaslevesque** [comment]
You can add a handler for the `Application.Current.DispatcherUnhandledException` event (and possibly `AppDomain.CurrentDomain.UnhandledException`) and log the exception you get there. Try to include as much information as possible, e.g. exception message, inner exception, HRESULT, etc. I don't know Application Insights, so I don't know how you can use it to retrieve the log, but I assume it must be possible...

**Comment by Dhirajsakariya** [comment]
I already added this event. I will try to reproduce exception and share the
details with you soon.

**Comment by Dhirajsakariya** [comment]
Hi Thomas,

I have spent time and created sample app to reproduce the issue.

I have two button to load user control. Each user control has spinner.

In my product , I amable to reproduce it very frequently.

In sample app , to reproduce the issue, I have use time to load user
control alternatively.

As this issue is related with threading, some times it reproduce
immediately and sometime it take some more time.

Please find the attached sample example.

Please don't hesitate to mail me if you need any further inputs.

With Regards,
Dhiraj

**Comment by thomaslevesque** [comment]
Thanks @Dhirajsakariya, that should be helpful! I'll look into it and see if I can reproduce the issue.

**Comment by thomaslevesque** [comment]
But it seems you forgot the attachment ;)

**Comment by Dhirajsakariya** [comment]
It is already attached (file name :ProjectManagement.UI.zip)

Anyway I am attaching it again.

**Comment by thomaslevesque** [comment]
@Dhirajsakariya I still don't see the attachment... I think sending attachments when you reply to a Github issue by email isn't supported. Try adding it directly in the Github UI.

**Comment by Dhirajsakariya** [comment]
[ProjectManagement.UI.zip](https://github.com/XamlAnimatedGif/WpfAnimatedGif/files/1554824/ProjectManagement.UI.zip)

Please find the attached zip file.

**Comment by thomaslevesque** [comment]
Thanks 👍

**Comment by thomaslevesque** [comment]
I'm unable to run your sample project. I had to make a lot of changes just to build it, and then it fails to run because of missing resources. Please remove anything that's not strictly necessary (e.g. references to EF, SendGrid, DevExpress, etc) and make sure it contains everything necessary to build and run.

**Comment by thomaslevesque** [comment]
I managed to make it run. It's been running for a while, and I haven't seen any error yet. I'll let it run a bit longer, just in case...

**Comment by thomaslevesque** [comment]
OK, I'm see a COMException, but with a different stack trace and message...

Message: MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003)

   at System.Windows.Media.Imaging.RenderTargetBitmap.CopyCommon(RenderTargetBitmap sourceBitmap)
   at System.Windows.Media.Imaging.RenderTargetBitmap.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCoreCommon(Freezable sourceFreezable, Boolean useCurrentValue, Boolean cloneFrozenValues)
   at System.Windows.Freezable.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectKeyFrameCollection.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.CopyCommon(ObjectAnimationUsingKeyFrames sourceAnimation, Boolean isCurrentValueClone)
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.GetCurrentValueAsFrozenCore(Freezable source)
   at System.Windows.Freezable.GetCurrentValueAsFrozen()
   at System.Windows.Media.Animation.Clock..ctor(Timeline timeline)
   at System.Windows.Media.Animation.AnimationTimeline.AllocateClock()
   at System.Windows.Media.Animation.Clock.AllocateClock(Timeline timeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.Clock.BuildClockTreeFromTimeline(Timeline rootTimeline, Boolean hasControllableRoot)
   at WpfAnimatedGif.ImageAnimationController..ctor(Image image, ObjectAnimationUsingKeyFrames animation, Boolean autoStart)
   at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(Image imageControl)
   at WpfAnimatedGif.ImageBehavior.ImageControlLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

But that's an internal WPF error that seems to occur randomly, I don't think there's anything I can do about it...

**Comment by Dhirajsakariya** [comment]
yes, Thomas.

I am getting this error now as you mentioned.

if I comment out the wpf spinner then there is no exception.

**Comment by thomaslevesque** [comment]
OK, I think I can guess what's going on : the process is using too many GDI handles. These handles are allocated by `RenderTargetBitmap`, and released when the object is finalized. Finalization occurs only when the GC collects the object, which it does if memory usage gets too high, but it doesn't consider GDI handle count to trigger a collection. So, sometimes, the GDI handle count can exceed the limit before the GC runs.

Running `GC.Collect(); GC.WaitForPendingFinalizers();` frequently should help prevent the error.

**Comment by thomaslevesque** [comment]
@Dhirajsakariya,

> Running GC.Collect(); GC.WaitForPendingFinalizers(); frequently should help prevent the error.

Have you tried this? Did it change anything?

**Comment by shrutisingh1993** [comment]
@Dhirajsakariya I tried this. I am now getting OutofMemory exception. I am simply rendering my animated GIF to the screen via WPF.

**Comment by cmjacobs** [comment]
There seems to be a correlation between frame count and the occurrence of these errors. I re-rendered my GIF's with a much lower frame count (they are screen cap videos so i removed a lot of duplicate frames and extended the duration of the frames I left) and the errors went away.

**Comment by thomaslevesque** [comment]
Closing due to inactivity
