### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sukney** [XamlAnimatedGif/WpfAnimatedGif#82]
MILERR_WIN32ERROR (0x88980003)
   at System.Windows.Media.Imaging.WriteableBitmap.InitFromBitmapSource(BitmapSource source)
   at System.Windows.Media.Imaging.WriteableBitmap.CopyCommon(WriteableBitmap sourceBitmap)
   at System.Windows.Media.Imaging.WriteableBitmap.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCoreCommon(Freezable sourceFreezable, Boolean useCurrentValue, Boolean cloneFrozenValues)
   at System.Windows.Freezable.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectKeyFrameCollection.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.CopyCommon(ObjectAnimationUsingKeyFrames sourceAnimation, Boolean isCurrentValueClone)
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.GetCurrentValueAsFrozenCore(Freezable source)
   at System.Windows.Freezable.GetCurrentValueAsFrozen()
   at System.Windows.Media.Animation.Clock..ctor(Timeline timeline)
   at System.Windows.Media.Animation.AnimationTimeline.AllocateClock()
   at System.Windows.Media.Animation.Clock.AllocateClock(Timeline timeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.Clock.BuildClockTreeFromTimeline(Timeline rootTimeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.AnimationTimeline.CreateClock()
   at WpfAnimatedGif.ImageAnimationController..ctor(Image image, ObjectAnimationUsingKeyFrames animation, Boolean autoStart)
   at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(Image imageControl)
   at WpfAnimatedGif.ImageBehavior.ImageControlLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by thomaslevesque** [comment]
I can't do anything about this issue if you don't provide some context. What were you trying to do, when did it happen, what's the GIF image that caused the issue, what platform are you targeting, etc.
In other words: if you can't make the effort to provide some useful information, I won't make the effort to investigate the issue...
